// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SICalcWebApp.Data;

#nullable disable

namespace SICalcWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250411122812_AddFrkCheckbox")]
    partial class AddFrkCheckbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.BatchProcessReport", b =>
                {
                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DryerDelay")
                        .HasColumnType("float");

                    b.Property<double>("DryerHandiTimeDifference")
                        .HasColumnType("float");

                    b.Property<DateTime>("DryerLoadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DryerStaff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DryerTakenTime")
                        .HasColumnType("float");

                    b.Property<string>("DryerUnloadBunk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DryerUnloadTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("DuctiPressure")
                        .HasColumnType("float");

                    b.Property<double>("HandiDelay")
                        .HasColumnType("float");

                    b.Property<DateTime>("HandiEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HandiStaff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HandiStartTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("HandiTakenTime")
                        .HasColumnType("float");

                    b.Property<string>("HandiType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MillBunkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MillEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MillStartTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("MillingDelay")
                        .HasColumnType("float");

                    b.Property<string>("MillingStaff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MillingTakenTime")
                        .HasColumnType("float");

                    b.Property<string>("PaddyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pressure")
                        .HasColumnType("float");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SortexDelay")
                        .HasColumnType("float");

                    b.Property<DateTime>("SortexEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SortexStaff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SortexStartTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("SortexTakenTime")
                        .HasColumnType("float");

                    b.Property<string>("SortexUnloadBunk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortexloadBunk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BatchProcessReports");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.DryerProcess", b =>
                {
                    b.Property<int>("DryerProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DryerProcessId"));

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DuctiPressure")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<DateTime?>("LoadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PauseReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PauseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResumeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("TotalDelayTime")
                        .HasColumnType("time");

                    b.Property<string>("UnloadBunkerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UnloadTime")
                        .HasColumnType("datetime2");

                    b.HasKey("DryerProcessId");

                    b.ToTable("DryerProcesses");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.FeedingBunker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FeedingBName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FeedingBunkers");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.FeedingModuleF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FeedingBunkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FeedingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfBags")
                        .HasColumnType("int");

                    b.Property<string>("PaddyTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FeedingModuleFs");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.GroupMill", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("GroupMills");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.HandiProcess", b =>
                {
                    b.Property<int>("HandiProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HandiProcessId"));

                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HandiType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PaddyMoisture")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("PaddyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PaddyWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PauseReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PauseTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Pressure")
                        .HasColumnType("float");

                    b.Property<string>("ProcessStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResumeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("TotalDelayTime")
                        .HasColumnType("time");

                    b.Property<string>("UnloadBunkerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaterType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HandiProcessId");

                    b.ToTable("HandiProcesses");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.HmaliInput", b =>
                {
                    b.Property<int>("HmaliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HmaliId"));

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HmaliId");

                    b.ToTable("HmaliInputs");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.MillBunker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MillBName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MillBunkers");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.MillItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.HasIndex("GroupId");

                    b.ToTable("MillItems");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.MillQuality", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BatchID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Machine_Broken")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Machine_Damage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Machine_Discolour")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Machine_FRK")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Machine_Moisture")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Manual_Broken")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Manual_Damage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Manual_Discolour")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Manual_FRK")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Manual_Moisture")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Mill_Wightment")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Moisture_Chotti_Machine")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Moisture_Chotti_Machine_Manual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Other1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("ID");

                    b.HasIndex("BatchID", "Stage")
                        .IsUnique();

                    b.ToTable("MillQualities");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.MillQualitySortex", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BatchID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Machine_Broken")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Machine_Damage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Machine_Discolour")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Machine_FRK")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Machine_Moisture")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Manual_Broken")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Manual_Damage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Manual_Discolour")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Manual_FRK")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Manual_Moisture")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Min10Rejection")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Moisture_Chotti_Machine")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Moisture_Chotti_Machine_Manual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Other1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Sec30Final")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("ID");

                    b.HasIndex("BatchID", "Stage")
                        .IsUnique();

                    b.ToTable("MillQualitySortexes");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.MillingProcess", b =>
                {
                    b.Property<int>("MillingProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MillingProcessId"));

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MillBunkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PauseReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PauseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResumeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SaleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortexBunkerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("TotalDelayTime")
                        .HasColumnType("time");

                    b.HasKey("MillingProcessId");

                    b.ToTable("MillingProcesses");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.PaddyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaddyTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PaddyTypes");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.ProcessMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessMethods");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.SortexBunker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("SortexBName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SortexBunkers");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.SortexProcess", b =>
                {
                    b.Property<int>("SortexProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SortexProcessId"));

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EndWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsFRK")
                        .HasColumnType("bit");

                    b.Property<string>("PauseReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PauseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResumeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SaleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortexBunkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("TotalDelayTime")
                        .HasColumnType("time");

                    b.HasKey("SortexProcessId");

                    b.ToTable("SortexProcesses");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.TypeOfHandi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeHandiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfHandis");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.VM.BatchProcessReportArwaVM", b =>
                {
                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HandiDelay")
                        .HasColumnType("float");

                    b.Property<DateTime>("HandiEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HandiStaff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HandiStartTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("HandiTakenTime")
                        .HasColumnType("float");

                    b.Property<string>("HandiType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MillBunkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MillEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MillStartTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("MillingDelay")
                        .HasColumnType("float");

                    b.Property<string>("MillingStaff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MillingTakenTime")
                        .HasColumnType("float");

                    b.Property<string>("PaddyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pressure")
                        .HasColumnType("float");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SortexDelay")
                        .HasColumnType("float");

                    b.Property<DateTime>("SortexEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SortexStaff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SortexStartTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("SortexTakenTime")
                        .HasColumnType("float");

                    b.Property<string>("SortexUnloadBunk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortexloadBunk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BatchProcessReportArwaVMs");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.SICalculator.Models.FC", b =>
                {
                    b.Property<int>("FCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FCId"));

                    b.Property<decimal>("C_Fe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FCValue")
                        .HasColumnType("int");

                    b.HasKey("FCId");

                    b.ToTable("FCs");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.SICalculator.Models.FCInfo", b =>
                {
                    b.Property<int>("FCInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FCInfoId"));

                    b.Property<int>("FCId")
                        .HasColumnType("int");

                    b.Property<decimal>("FeedRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TPDId")
                        .HasColumnType("int");

                    b.HasKey("FCInfoId");

                    b.HasIndex("FCId");

                    b.HasIndex("TPDId");

                    b.ToTable("FCInfos");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.SICalculator.Models.InputOperand", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<decimal>("FeMSponge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FeT")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FineLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FinesRealisationValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Gangue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GroundLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("IronPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IronTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Moisture")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Phos")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Sidename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TransferLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("YLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Yield")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ProductID");

                    b.HasIndex("IronTypeId");

                    b.ToTable("InputOperands");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.SICalculator.Models.IronType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IronTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IronTypes");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.SICalculator.Models.PriceOfMaterial", b =>
                {
                    b.Property<int>("PriceInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceInputId"));

                    b.Property<decimal>("DolomiteRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MgfExpence")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PriceInputId");

                    b.ToTable("PriceOfMaterials");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.SICalculator.Models.TPDInfo", b =>
                {
                    b.Property<int>("TPDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TPDId"));

                    b.Property<string>("KilnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TPD")
                        .HasColumnType("int");

                    b.HasKey("TPDId");

                    b.ToTable("TPDInfos");
                });

            modelBuilder.Entity("SICalcWebApp.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.MillItem", b =>
                {
                    b.HasOne("SICalcWebApp.Areas.RiceMill.Models.GroupMill", "GroupMill")
                        .WithMany("MillItems")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMill");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.SICalculator.Models.FCInfo", b =>
                {
                    b.HasOne("SICalcWebApp.Areas.SICalculator.Models.FC", "FC")
                        .WithMany("FCInfos")
                        .HasForeignKey("FCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICalcWebApp.Areas.SICalculator.Models.TPDInfo", "TPDInfo")
                        .WithMany("FCInfos")
                        .HasForeignKey("TPDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FC");

                    b.Navigation("TPDInfo");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.SICalculator.Models.InputOperand", b =>
                {
                    b.HasOne("SICalcWebApp.Areas.SICalculator.Models.IronType", "IronType")
                        .WithMany()
                        .HasForeignKey("IronTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IronType");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.RiceMill.Models.GroupMill", b =>
                {
                    b.Navigation("MillItems");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.SICalculator.Models.FC", b =>
                {
                    b.Navigation("FCInfos");
                });

            modelBuilder.Entity("SICalcWebApp.Areas.SICalculator.Models.TPDInfo", b =>
                {
                    b.Navigation("FCInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
